version: '3'

services:
    db:
        image: mariadb
        container_name: db
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        ports:
            ['3306:3306']
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

    django:
        build: ./django
        container_name: django
        restart: always
        entrypoint: [ "/bin/bash", "docker-entrypoint.sh" ]
        command: uwsgi --ini uwsgi.ini --static-map /static=./static
        volumes:
            - ./django:/app
        working_dir: /app
        ports:
            ['8001']
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
            - DJANGO_SUPERUSER_NAME
            - DJANGO_SUPERUSER_PASSWORD
        depends_on:
            db:
                condition: service_healthy
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/api-proxy.conf:/etc/nginx/sites-available/api-proxy.connf
        ports:
            ['80:80']
        depends_on:
            - django
volumes:
    db_data:
